//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptocurrenciesWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptocurrenciesWPF.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string chartAxisDate {
            get {
                return ResourceManager.GetString("chartAxisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string chartAxisPrice {
            get {
                return ResourceManager.GetString("chartAxisPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string listHeaderBase {
            get {
                return ResourceManager.GetString("listHeaderBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string listHeaderExchange {
            get {
                return ResourceManager.GetString("listHeaderExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Usd.
        /// </summary>
        public static string listHeaderPriceUsd {
            get {
                return ResourceManager.GetString("listHeaderPriceUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string listHeaderQuote {
            get {
                return ResourceManager.GetString("listHeaderQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string menuList {
            get {
                return ResourceManager.GetString("menuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulation Supply.
        /// </summary>
        public static string textBlocCirculationSupply {
            get {
                return ResourceManager.GetString("textBlocCirculationSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        public static string textBlockMarketCap {
            get {
                return ResourceManager.GetString("textBlockMarketCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Market Information.
        /// </summary>
        public static string textBlockMarketInformation {
            get {
                return ResourceManager.GetString("textBlockMarketInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string textBlockPopularity {
            get {
                return ResourceManager.GetString("textBlockPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Purchase Markets.
        /// </summary>
        public static string textBlockPurchaseMarkets {
            get {
                return ResourceManager.GetString("textBlockPurchaseMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string textBlockSearch {
            get {
                return ResourceManager.GetString("textBlockSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume (24hours).
        /// </summary>
        public static string textBlockVolume24HR {
            get {
                return ResourceManager.GetString("textBlockVolume24HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF Title.
        /// </summary>
        public static string windowTitle {
            get {
                return ResourceManager.GetString("windowTitle", resourceCulture);
            }
        }
    }
}
